version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:14.0
    steps:
      - checkout
      - run:
          name: Install Chromium for Playwright
          command: mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install chrome"
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - store_test_results:
          path: ./reports/junit
workflows:
  sample: 
    jobs:
      - build-and-test
