package qa.enums;

public enum SideMenuURLs {

    NEW_ARCHBISHOP,
    PARISH_STATISTICS,
    RETRANSMISSION,
    FORGIVENESS_REPORT,
    PLENARY_INDULGENCE,
    LITANY,
    PARISH_HISTORY,
    YESTERDAY_AND_NOW,
    BASILICA_INSIDE,
    PARISH_COMMUNITY,
    SACRAMENTS,
    CALVARY,
    PHOTO_GALLERY,
    FILMS,
    EVENING_WITH_JESUS,
    CEMENTERY_REGULATIONS,
    DELEGATE,
    PARISH_CHARITABLE_ACTIVITIES
}
